[workspace]
members = ["2015/*", "2016/*", "2023/*"]
exclude = ["2022/*"]
resolver = "2"

[workspace.package]
rust-version = "1.78.0"

[workspace.dependencies]
log = "0.4.21"
env_logger = "0.11.3"
itertools = "0.12.1"
nom = "7.1.3"
rand = "0.8.5"
md5 = "0.7.0"
serde_json = "1.0.117"
generator = "0.8.1"
ndarray = "0.15.6"
regex = "1.10.4"
num = "0.4.3"
