[workspace]
members = ["2015/*", "2016/*"]
exclude = ["2022/*"]
resolver = "2"

[workspace.package]
rust-version = "1.72.1"

[workspace.dependencies]
log = "0.4.20"
env_logger = "0.10.0"
itertools = "0.11.0"
nom = "7.1.3"
rand = "0.8.5"
md5 = "0.7.0"
serde_json = "1.0.107"
generator = "0.7.5"
ndarray = "0.15.6"
regex = "1.9.6"
