[package]
name = "day13_knights_of_the_dinner_table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
env_logger = "*"
itertools = "*"
nom = "*"
