[package]
name = "day13_knights_of_the_dinner_table"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true
env_logger.workspace = true
itertools.workspace = true
nom.workspace = true
