[package]
name = "day19_medicine_for_rudolph"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true
env_logger.workspace = true
nom.workspace = true
itertools.workspace = true
regex.workspace = true
