[package]
name = "day15_science_for_hungry_people"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
env_logger = "*"
nom = "*"
generator = "0.7"
