[package]
name = "day12_jsabacusframework_io"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
log.workspace = true
env_logger.workspace = true
serde_json.workspace = true
