[package]
name = "day05_if_you_give_a_seed_a_fertilizer"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
log.workspace = true
env_logger.workspace = true
nom.workspace = true
