[package]
name = "day18_lavaduct_lagoon"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
log.workspace = true
env_logger.workspace = true
nom.workspace = true
ndarray.workspace = true
