[package]
name = "day10_elves_look_elves_say"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
log.workspace = true
env_logger.workspace = true
itertools.workspace = true
