name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_solutions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Instal Rust toolchain"
        uses: dtolnay/rust-toolchain@1.71.0
      - name: Build all solutions
        run: cargo build
      - name: Run tests on all solutions
        run: cargo test
